import { supabaseAdmin } from "@/integrations/supabase/client.server";

type QueueItem={id:string;recipient_id:string;subject:string;body_text:string};
type Transport={provider:string;enabled:boolean;host:string;port:number;secure:boolean;username:string;password:string;from_name:string|null;from_email:string;reply_to:string|null};
type RpcResult<T>={data:T|null;error:{message:string}|null};
async function rpc<T>(name:string,args?:Record<string,unknown>):Promise<RpcResult<T>>{const call=supabaseAdmin.rpc as unknown as(fn:string,p?:Record<string,unknown>)=>PromiseLike<RpcResult<T>>;return call(name,args)}
function escapeHtml(v:string){return v.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}
function html(text:string){return `<div style="font-family:Arial,sans-serif;max-width:620px;margin:auto;color:#351810"><h2 style="color:#9f3d25">Inimigos do Fim</h2><p>${escapeHtml(text)}</p><p style="margin-top:28px;font-size:13px;color:#755348">Gerencie suas preferências na central de notificações.</p></div>`}
async function sendBrevo(config:Transport,to:string,subject:string,text:string){const response=await fetch("https://api.brevo.com/v3/smtp/email",{method:"POST",headers:{"content-type":"application/json","api-key":config.password},body:JSON.stringify({sender:{name:config.from_name||"Inimigos do Fim",email:config.from_email},to:[{email:to}],subject,textContent:text,htmlContent:html(text)})});const body=await response.text();if(!response.ok)throw new Error(`Falha no provedor (${response.status})`);try{return (JSON.parse(body) as {messageId?:string}).messageId||null}catch{return null}}
export async function processEmailDeliveryQueue(options:{limit?:number}={}){const cfg=await rpc<Transport>("get_email_transport_secret");if(cfg.error)throw new Error(cfg.error.message);const config=cfg.data;if(!config?.enabled)return{ok:true,processed:0,sent:0,failed:0,skipped:"disabled"};if(config.provider!=="brevo")return{ok:true,processed:0,sent:0,failed:0,skipped:"smtp_gateway_pending"};const batch=await rpc<QueueItem[]>("claim_email_delivery_batch",{batch_size:Math.max(1,Math.min(options.limit||20,50))});if(batch.error)throw new Error(batch.error.message);let sent=0,failed=0;for(const item of batch.data||[]){try{const user=await supabaseAdmin.auth.admin.getUserById(item.recipient_id);if(user.error||!user.data.user?.email)throw new Error("Destinatário indisponível");const messageId=await sendBrevo(config,user.data.user.email,item.subject,item.body_text);await rpc("complete_email_delivery",{queue_id:item.id,success:true,error_message:null,external_message_id:messageId});sent++}catch(error){failed++;await rpc("complete_email_delivery",{queue_id:item.id,success:false,error_message:error instanceof Error?error.message:"Falha desconhecida",external_message_id:null})}}return{ok:true,processed:(batch.data||[]).length,sent,failed}}
