import { createFileRoute } from "@tanstack/react-router";
import { CheckCircle2, Clock3, Flag, Loader2, ShieldCheck, XCircle } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { EcosystemHeader } from "@/components/community/EcosystemHeader";
import { supabase } from "@/integrations/supabase/client";

export const Route = createFileRoute("/admin-moderation")({ component: AdminModerationPage });
type Report = { id:string; reporter_id:string; entity_type:string; entity_id:string; reason:string; details:string|null; status:string; created_at:string; assigned_to?:string|null; resolution_notes?:string|null };
type SafetyClient = typeof supabase & { rpc:(fn:string,args?:Record<string,unknown>)=>Promise<{data:unknown;error:{message:string}|null}> };
const client=supabase as SafetyClient;

function AdminModerationPage(){
 const [authorized,setAuthorized]=useState<boolean|null>(null),[reports,setReports]=useState<Report[]>([]),[filter,setFilter]=useState("open"),[busy,setBusy]=useState<string|null>(null),[notes,setNotes]=useState<Record<string,string>>({});
 const load=useCallback(async()=>{const{data:auth}=await supabase.auth.getUser();if(!auth.user){setAuthorized(false);return}const{data:admin}=await supabase.from("admin_users").select("id").eq("id",auth.user.id).maybeSingle();if(!admin){setAuthorized(false);return}setAuthorized(true);const{data,error}=await supabase.from("community_reports" as never).select("*").order("created_at",{ascending:false}).limit(200) as unknown as {data:Report[]|null;error:{message:string}|null};if(error){toast.error(error.message);return}setReports(data??[])},[]);
 useEffect(()=>{void load()},[load]);
 const visible=useMemo(()=>filter==="all"?reports:reports.filter(r=>r.status===filter),[reports,filter]);
 async function decide(report:Report,decision:"pending"|"resolved"|"dismissed"){setBusy(report.id);const{error}=await client.rpc("moderate_community_report",{target_report_id:report.id,decision,notes:notes[report.id]?.trim()||null});setBusy(null);if(error){toast.error(error.message);return}toast.success(decision==="pending"?"Denúncia assumida para análise.":decision==="resolved"?"Denúncia resolvida.":"Denúncia arquivada.");await load()}
 if(authorized===null)return <div className="grid min-h-screen place-items-center bg-[#fffaf3]"><Loader2 className="size-8 animate-spin text-[#9f3d25]"/></div>;
 if(!authorized)return <div className="min-h-screen bg-[#fffaf3] text-[#351810]"><EcosystemHeader/><main className="mx-auto max-w-2xl px-4 py-20 text-center"><ShieldCheck className="mx-auto size-12 text-[#9f3d25]"/><h1 className="mt-4 text-3xl font-black">Área administrativa</h1><p className="mt-2 text-[#755348]">Esta central é restrita à equipe de moderação.</p></main></div>;
 const counts={open:reports.filter(r=>r.status==="open").length,pending:reports.filter(r=>r.status==="pending").length,resolved:reports.filter(r=>r.status==="resolved").length,dismissed:reports.filter(r=>r.status==="dismissed").length};
 return <div className="min-h-screen bg-[#fffaf3] text-[#351810]"><EcosystemHeader/><main className="mx-auto max-w-6xl px-4 py-10"><div className="flex items-start gap-3"><ShieldCheck className="mt-1 size-9 text-[#9f3d25]"/><div><p className="text-xs font-black uppercase tracking-widest text-[#9f3d25]">Administração</p><h1 className="text-4xl font-black">Central de moderação</h1><p className="mt-2 text-[#755348]">Fila única de denúncias da comunidade, chats, publicações e marketplace.</p></div></div>
 <section className="mt-7 grid gap-3 sm:grid-cols-4">{[["open","Abertas",counts.open],["pending","Em análise",counts.pending],["resolved","Resolvidas",counts.resolved],["dismissed","Arquivadas",counts.dismissed]].map(([key,label,count])=><button key={String(key)} onClick={()=>setFilter(String(key))} className={`rounded-2xl border p-4 text-left ${filter===key?"border-[#9f3d25] bg-[#fff0e6]":"border-[#ead9ca] bg-white"}`}><span className="text-xs font-bold uppercase tracking-wide text-[#755348]">{label}</span><strong className="mt-1 block text-3xl">{count}</strong></button>)}</section>
 <div className="mt-4 flex justify-end"><button onClick={()=>setFilter("all")} className="text-sm font-bold text-[#9f3d25]">Ver todas</button></div>
 <section className="mt-5 grid gap-4">{visible.map(report=><article key={report.id} className="rounded-3xl border border-[#ead9ca] bg-white p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex min-w-0 gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-2xl bg-[#f4e6d7] text-[#9f3d25]"><Flag className="size-5"/></span><div><div className="flex flex-wrap gap-2"><span className="rounded-full bg-[#fff3c9] px-2.5 py-1 text-xs font-bold">{report.entity_type}</span><span className="rounded-full bg-[#f4e6d7] px-2.5 py-1 text-xs font-bold">{report.status}</span></div><h2 className="mt-2 text-lg font-black">{report.reason}</h2><p className="mt-1 whitespace-pre-line text-sm text-[#755348]">{report.details||"Sem detalhes adicionais."}</p><p className="mt-2 text-xs text-[#8a5c4d]">Recebida em {new Date(report.created_at).toLocaleString("pt-BR")}</p></div></div></div>
 <label className="mt-4 block text-sm font-bold">Notas internas<textarea value={notes[report.id]??report.resolution_notes??""} onChange={e=>setNotes(c=>({...c,[report.id]:e.target.value}))} rows={2} maxLength={1500} className="mt-2 w-full rounded-xl border border-[#ead9ca] px-4 py-3 font-normal" placeholder="Contexto da análise e providências adotadas"/></label>
 <div className="mt-4 flex flex-wrap justify-end gap-2">{report.status==="open"?<button disabled={busy===report.id} onClick={()=>void decide(report,"pending")} className="inline-flex items-center gap-2 rounded-xl border border-[#d8bca8] px-4 py-2.5 text-sm font-bold"><Clock3 className="size-4"/>Assumir análise</button>:null}<button disabled={busy===report.id} onClick={()=>void decide(report,"dismissed")} className="inline-flex items-center gap-2 rounded-xl border border-red-200 px-4 py-2.5 text-sm font-bold text-red-700"><XCircle className="size-4"/>Arquivar</button><button disabled={busy===report.id} onClick={()=>void decide(report,"resolved")} className="inline-flex items-center gap-2 rounded-xl bg-[#9f3d25] px-4 py-2.5 text-sm font-bold text-white">{busy===report.id?<Loader2 className="size-4 animate-spin"/>:<CheckCircle2 className="size-4"/>}Resolver</button></div></article>)}{!visible.length?<div className="rounded-3xl border-2 border-dashed border-[#ead9ca] p-10 text-center text-[#755348]">Nenhuma denúncia nesta fila.</div>:null}</section></main></div>
}