import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import {
  ArrowLeft, Download, FileText, Loader2, Lock, LogOut, Paperclip, Pencil,
  Reply, Save, Send, Trash2, UserMinus, UserPlus, Users, X,
} from "lucide-react";
import { type ChangeEvent, useCallback, useEffect, useState } from "react";
import { toast } from "sonner";

import { EcosystemHeader } from "@/components/community/EcosystemHeader";
import { supabase } from "@/integrations/supabase/client";
import type { Tables } from "@/integrations/supabase/database";

export const Route = createFileRoute("/chats/$roomId")({ component: ChatRoomPage });
const PRIVATE_BUCKET = "community-private-files";
const MAX_FILE_SIZE = 25 * 1024 * 1024;
const ALLOWED_TYPES = new Set(["image/png","image/jpeg","image/webp","application/pdf","audio/mpeg","audio/ogg","audio/mp4","video/mp4","video/webm"]);
type Room = Tables<"chat_rooms">;
type Message = Tables<"chat_messages">;
type Member = Tables<"chat_room_members">;
type Profile = Pick<Tables<"community_profiles">,"id"|"display_name"|"artistic_name"|"avatar_url"|"profile_type">;
function profileName(profile?: Profile) { return profile?.artistic_name || profile?.display_name || "Membro"; }
function attachmentKind(path:string){const e=path.split(".").pop()?.toLowerCase();if(["jpg","jpeg","png","webp"].includes(e??""))return"image";if(["mp3","ogg","m4a"].includes(e??""))return"audio";if(["mp4","webm"].includes(e??""))return"video";return"document";}
function attachmentLabel(path:string){return(path.split("/").pop()??"arquivo").replace(/^[0-9a-f-]{36}-/,"");}
function ChatAttachment({path,signedUrl,own}:{path:string;signedUrl?:string;own:boolean}){if(!signedUrl)return <span className="mt-2 block text-xs opacity-70">Preparando arquivo…</span>;const k=attachmentKind(path);if(k==="image")return <a href={signedUrl} target="_blank" rel="noreferrer"><img src={signedUrl} alt={attachmentLabel(path)} className="mt-3 max-h-72 w-full rounded-xl object-cover"/></a>;if(k==="audio")return <audio controls preload="metadata" className="mt-3 max-w-full"><source src={signedUrl}/></audio>;if(k==="video")return <video controls preload="metadata" className="mt-3 max-h-72 w-full rounded-xl"><source src={signedUrl}/></video>;return <a href={signedUrl} target="_blank" rel="noreferrer" className={`mt-3 flex items-center gap-2 rounded-xl border px-3 py-2 text-sm font-bold ${own?"border-white/30":"border-[#9f3d25]/20"}`}><FileText className="size-4"/><span className="min-w-0 flex-1 truncate">{attachmentLabel(path)}</span><Download className="size-4"/></a>}

function ChatRoomPage(){
 const {roomId}=Route.useParams(); const navigate=useNavigate();
 const [userId,setUserId]=useState<string|null>(null),[room,setRoom]=useState<Room|null>(null),[messages,setMessages]=useState<Message[]>([]),[members,setMembers]=useState<Member[]>([]);
 const [profiles,setProfiles]=useState<Record<string,Profile>>({}),[availableProfiles,setAvailableProfiles]=useState<Profile[]>([]),[signedUrls,setSignedUrls]=useState<Record<string,string>>({});
 const [body,setBody]=useState(""),[files,setFiles]=useState<File[]>([]),[loading,setLoading]=useState(true),[sending,setSending]=useState(false),[managing,setManaging]=useState(false),[changingMemberId,setChangingMemberId]=useState<string|null>(null);
 const [replyTo,setReplyTo]=useState<Message|null>(null),[editing,setEditing]=useState(false),[editName,setEditName]=useState(""),[editDescription,setEditDescription]=useState(""),[savingRoom,setSavingRoom]=useState(false),[leaving,setLeaving]=useState(false);
 const loadConversation=useCallback(async()=>{const [rr,mr,mer]=await Promise.all([supabase.from("chat_rooms").select("*").eq("id",roomId).maybeSingle(),supabase.from("chat_messages").select("*").eq("room_id",roomId).order("created_at",{ascending:true}),supabase.from("chat_room_members").select("*").eq("room_id",roomId)]);const lm=mr.data??[], lmem=mer.data??[];setRoom(rr.data);setMessages(lm);setMembers(lmem);const ids=[...new Set([...lmem.map(m=>m.profile_id),...lm.map(m=>m.sender_id)])];const paths=[...new Set(lm.filter(m=>!m.deleted_at).flatMap(m=>m.media_urls))];const [pr,sr]=await Promise.all([ids.length?supabase.from("community_profiles").select("id,display_name,artistic_name,avatar_url,profile_type").in("id",ids):Promise.resolve({data:[] as Profile[]}),paths.length?supabase.storage.from(PRIVATE_BUCKET).createSignedUrls(paths,3600):Promise.resolve({data:[]})]);setProfiles(Object.fromEntries((pr.data??[]).map(p=>[p.id,p])));setSignedUrls(Object.fromEntries((sr.data??[]).filter(i=>i.signedUrl).map(i=>[i.path,i.signedUrl])));const last=lm.at(-1);void supabase.rpc("mark_chat_read",{target_room_id:roomId,read_through:last?.created_at??new Date().toISOString()});},[roomId]);
 useEffect(()=>{let channel:ReturnType<typeof supabase.channel>|null=null;async function load(){const{data}=await supabase.auth.getUser();setUserId(data.user?.id??null);if(data.user){await loadConversation();channel=supabase.channel(`chat-${roomId}`).on("postgres_changes",{event:"*",schema:"public",table:"chat_messages",filter:`room_id=eq.${roomId}`},()=>void loadConversation()).subscribe()}setLoading(false)}void load();return()=>{if(channel)void supabase.removeChannel(channel)}},[loadConversation,roomId]);
 function selectFiles(e:ChangeEvent<HTMLInputElement>){const s=Array.from(e.target.files??[]);e.target.value="";if(s.find(f=>!ALLOWED_TYPES.has(f.type)||f.size>MAX_FILE_SIZE)){toast.error("Envie imagens, PDF, áudio ou vídeo com até 25 MB por arquivo.");return}setFiles(c=>[...c,...s])}
 async function sendMessage(){if(!userId||(!body.trim()&&!files.length))return;setSending(true);const paths:string[]=[];try{for(const file of files){const safe=file.name.normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zA-Z0-9._-]+/g,"-");const path=`${userId}/chat/${roomId}/${crypto.randomUUID()}-${safe}`;const{error}=await supabase.storage.from(PRIVATE_BUCKET).upload(path,file,{contentType:file.type,cacheControl:"3600",upsert:false});if(error)throw error;paths.push(path)}const{error}=await supabase.from("chat_messages").insert({room_id:roomId,sender_id:userId,body:body.trim()||null,media_urls:paths,reply_to_id:replyTo?.id??null});if(error)throw error;setBody("");setFiles([]);setReplyTo(null);await loadConversation()}catch(cause){if(paths.length)await supabase.storage.from(PRIVATE_BUCKET).remove(paths);toast.error(cause instanceof Error?cause.message:"Não foi possível enviar a mensagem.")}finally{setSending(false)}}
 async function deleteMessage(id:string){const{error}=await supabase.from("chat_messages").update({deleted_at:new Date().toISOString()}).eq("id",id);if(error)toast.error(error.message);else await loadConversation()}
 async function openMemberManager(){setManaging(true);const ids=new Set(members.map(m=>m.profile_id));const{data}=await supabase.from("community_profiles").select("id,display_name,artistic_name,avatar_url,profile_type").eq("visibility","public").order("display_name");setAvailableProfiles((data??[]).filter(p=>!ids.has(p.id)))}
 async function changeMember(id:string,operation:"add"|"remove"){setChangingMemberId(id);const{error}=await supabase.rpc("manage_chat_member",{target_room_id:roomId,target_profile_id:id,operation});setChangingMemberId(null);if(error){toast.error(error.message);return}toast.success(operation==="add"?"Pessoa adicionada.":"Pessoa removida.");await loadConversation();if(operation==="add")setAvailableProfiles(c=>c.filter(p=>p.id!==id))}
 function beginEdit(){if(!room)return;setEditName(room.name||"");setEditDescription(room.description||"");setEditing(true)}
 async function saveRoom(){if(!editName.trim())return;setSavingRoom(true);const{error}=await supabase.rpc("update_chat_room",{target_room_id:roomId,new_name:editName.trim(),new_description:editDescription.trim()||null});setSavingRoom(false);if(error){toast.error(error.message);return}setEditing(false);toast.success("Conversa atualizada.");await loadConversation()}
 async function leaveRoom(){if(!window.confirm("Deseja realmente sair desta conversa?"))return;setLeaving(true);const{error}=await supabase.rpc("leave_chat_room",{target_room_id:roomId});setLeaving(false);if(error){toast.error(error.message);return}toast.success("Você saiu da conversa.");void navigate({to:"/chats"})}
 if(loading)return <div className="grid min-h-screen place-items-center bg-[#fffaf3] text-[#9f3d25]"><Loader2 className="size-8 animate-spin"/></div>;
 if(!userId||!room)return <div className="min-h-screen bg-[#fffaf3] text-[#351810]"><EcosystemHeader/><main className="mx-auto max-w-3xl px-4 py-20 text-center"><Lock className="mx-auto size-10 text-[#9f3d25]"/><h1 className="mt-4 text-3xl font-black">Conversa privada</h1><p className="mt-3 text-[#755348]">Somente os membros convidados podem acessar este espaço.</p><Link to="/chats" className="mt-6 inline-flex items-center gap-2 font-bold text-[#9f3d25]"><ArrowLeft className="size-4"/>Voltar para conversas</Link></main></div>;
 const isOwner=room.owner_id===userId;
 return <div className="flex min-h-screen flex-col bg-[#fffaf3] text-[#351810]"><EcosystemHeader/><main className="mx-auto flex w-full max-w-4xl flex-1 flex-col px-4 py-6">
 <section className="rounded-3xl bg-[#351810] p-5 text-white"><Link to="/chats" className="inline-flex items-center gap-2 text-sm font-bold text-[#ffc857]"><ArrowLeft className="size-4"/>Conversas</Link><div className="mt-4 flex flex-wrap items-end justify-between gap-4"><div className="min-w-0 flex-1"><h1 className="text-3xl font-black">{room.name||"Conversa privada"}</h1><p className="mt-2 text-sm text-[#f1d5c7]">{room.description||"Espaço reservado para o projeto."}</p></div><div className="flex flex-wrap gap-2">{isOwner?<button type="button" onClick={beginEdit} className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-2 text-sm hover:bg-white/20"><Pencil className="size-4"/>Editar</button>:null}<button type="button" onClick={()=>isOwner?void openMemberManager():undefined} className={`inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-2 text-sm ${isOwner?"hover:bg-white/20":""}`}><Users className="size-4"/>{members.length}</button><button type="button" disabled={leaving} onClick={()=>void leaveRoom()} className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-2 text-sm hover:bg-white/20 disabled:opacity-50">{leaving?<Loader2 className="size-4 animate-spin"/>:<LogOut className="size-4"/>}Sair</button></div></div></section>
 {editing&&isOwner?<section className="mt-4 rounded-3xl border border-[#ead9ca] bg-white p-5"><div className="flex items-center justify-between"><h2 className="text-xl font-black">Editar conversa</h2><button onClick={()=>setEditing(false)}><X/></button></div><div className="mt-4 grid gap-3"><input value={editName} maxLength={100} onChange={e=>setEditName(e.target.value)} className="rounded-xl border border-[#ead9ca] px-4 py-3" placeholder="Nome da conversa"/><textarea value={editDescription} maxLength={600} onChange={e=>setEditDescription(e.target.value)} rows={3} className="rounded-xl border border-[#ead9ca] px-4 py-3" placeholder="Descrição"/><button disabled={savingRoom||editName.trim().length<2} onClick={()=>void saveRoom()} className="ml-auto inline-flex items-center gap-2 rounded-xl bg-[#9f3d25] px-4 py-2.5 font-bold text-white disabled:opacity-40">{savingRoom?<Loader2 className="size-4 animate-spin"/>:<Save className="size-4"/>}Salvar</button></div></section>:null}
 {managing&&isOwner?<section className="mt-4 rounded-3xl border border-[#ead9ca] bg-white p-5 shadow-lg"><div className="flex items-center justify-between"><div><h2 className="text-xl font-black">Participantes</h2><p className="text-sm text-[#755348]">Somente você pode adicionar ou remover pessoas.</p></div><button onClick={()=>setManaging(false)}><X/></button></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{members.map(m=>{const p=profiles[m.profile_id],n=profileName(p),owner=m.profile_id===room.owner_id;return <div key={m.profile_id} className="flex items-center gap-3 rounded-2xl bg-[#fffaf3] p-3">{p?.avatar_url?<img src={p.avatar_url} alt="" className="size-10 rounded-xl object-cover"/>:<span className="grid size-10 place-items-center rounded-xl bg-[#f4e6d7] font-black text-[#9f3d25]">{n[0]}</span>}<span className="min-w-0 flex-1"><strong className="block truncate">{n}</strong><small className="text-[#755348]">{owner?"Responsável":"Participante"}</small></span>{!owner?<button disabled={changingMemberId===m.profile_id} onClick={()=>void changeMember(m.profile_id,"remove")} className="text-red-700">{changingMemberId===m.profile_id?<Loader2 className="size-4 animate-spin"/>:<UserMinus className="size-4"/>}</button>:null}</div>})}</div>{availableProfiles.length?<div className="mt-5 border-t border-[#ead9ca] pt-4"><h3 className="font-bold">Adicionar pessoas</h3><div className="mt-3 grid max-h-64 gap-2 overflow-y-auto sm:grid-cols-2">{availableProfiles.map(p=><button key={p.id} disabled={changingMemberId===p.id} onClick={()=>void changeMember(p.id,"add")} className="flex items-center gap-3 rounded-2xl border border-[#ead9ca] p-3 text-left"><UserPlus className="size-4 text-[#9f3d25]"/><span className="min-w-0 flex-1 truncate font-bold">{profileName(p)}</span></button>)}</div></div>:null}</section>:null}
 <section className="mt-5 flex-1 space-y-3 rounded-3xl border border-[#ead9ca] bg-white p-4 md:p-6" aria-label="Mensagens">{messages.map(message=>{const own=message.sender_id===userId,p=profiles[message.sender_id],name=profileName(p),parent=message.reply_to_id?messages.find(m=>m.id===message.reply_to_id):undefined,parentName=parent?profileName(profiles[parent.sender_id]):"";return <article key={message.id} className={`flex gap-3 ${own?"flex-row-reverse":""}`}>{p?.avatar_url?<img src={p.avatar_url} alt="" className="size-9 rounded-xl object-cover"/>:<span className="grid size-9 shrink-0 place-items-center rounded-xl bg-[#f4e6d7] text-sm font-black text-[#9f3d25]">{name[0]}</span>}<div className={`max-w-[82%] rounded-2xl px-4 py-3 ${own?"bg-[#9f3d25] text-white":"bg-[#f4e6d7]"}`}><div className="flex items-center gap-3"><strong className="text-xs">{name}</strong><time className={`text-[11px] ${own?"text-white/70":"text-[#8a5c4d]"}`}>{new Date(message.created_at).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}</time></div>{parent?<button type="button" onClick={()=>document.getElementById(`message-${parent.id}`)?.scrollIntoView({behavior:"smooth",block:"center"})} className={`mt-2 block w-full rounded-lg border-l-4 p-2 text-left text-xs ${own?"border-white/60 bg-white/10":"border-[#9f3d25]/40 bg-white/60"}`}><strong>{parentName}</strong><span className="mt-0.5 block line-clamp-2">{parent.deleted_at?"Mensagem removida":parent.body||"Anexo"}</span></button>:null}<div id={`message-${message.id}`}><p className={`mt-1 whitespace-pre-wrap ${message.deleted_at?"italic opacity-65":""}`}>{message.deleted_at?"Mensagem removida":message.body}</p>{!message.deleted_at?message.media_urls.map(path=><ChatAttachment key={path} path={path} signedUrl={signedUrls[path]} own={own}/>):null}</div>{!message.deleted_at?<div className="mt-2 flex gap-3"><button type="button" onClick={()=>setReplyTo(message)} className="inline-flex items-center gap-1 text-xs opacity-75"><Reply className="size-3"/>Responder</button>{own?<button type="button" onClick={()=>void deleteMessage(message.id)} className="inline-flex items-center gap-1 text-xs opacity-75"><Trash2 className="size-3"/>Remover</button>:null}</div>:null}</div></article>})}{!messages.length?<div className="py-16 text-center text-[#755348]">Envie a primeira mensagem deste projeto.</div>:null}</section>
 {replyTo?<div className="mt-3 flex items-start gap-3 rounded-2xl border-l-4 border-[#9f3d25] bg-white p-3 text-sm"><Reply className="mt-0.5 size-4 text-[#9f3d25]"/><div className="min-w-0 flex-1"><strong>Respondendo a {profileName(profiles[replyTo.sender_id])}</strong><p className="truncate text-[#755348]">{replyTo.body||"Anexo"}</p></div><button onClick={()=>setReplyTo(null)}><X className="size-4"/></button></div>:null}
 {files.length?<div className="mt-3 flex flex-wrap gap-2">{files.map((file,index)=><span key={`${file.name}-${index}`} className="inline-flex max-w-full items-center gap-2 rounded-full bg-[#f4e6d7] px-3 py-2 text-xs"><Paperclip className="size-3"/><span className="max-w-52 truncate">{file.name}</span><button onClick={()=>setFiles(c=>c.filter((_,i)=>i!==index))}><X className="size-3"/></button></span>)}</div>:null}
 <form className="sticky bottom-0 mt-3 flex gap-2 bg-[#fffaf3] py-3" onSubmit={e=>{e.preventDefault();void sendMessage()}}><label className="grid size-14 shrink-0 cursor-pointer place-items-center self-end rounded-2xl border border-[#ead9ca] bg-white text-[#9f3d25]"><Paperclip className="size-5"/><input type="file" multiple accept="image/png,image/jpeg,image/webp,application/pdf,audio/mpeg,audio/ogg,audio/mp4,video/mp4,video/webm" className="sr-only" onChange={selectFiles}/></label><textarea value={body} onChange={e=>setBody(e.target.value)} rows={2} placeholder={replyTo?"Escreva sua resposta...":"Escreva uma mensagem..."} className="min-w-0 flex-1 resize-none rounded-2xl border border-[#ead9ca] bg-white px-4 py-3 outline-none focus:border-[#9f3d25]"/><button type="submit" disabled={sending||(!body.trim()&&!files.length)} className="grid size-14 shrink-0 place-items-center self-end rounded-2xl bg-[#9f3d25] text-white disabled:opacity-40">{sending?<Loader2 className="size-5 animate-spin"/>:<Send className="size-5"/>}</button></form>
 </main></div>
}