import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, Loader2, ShieldCheck } from "lucide-react";
import { type FormEvent, useEffect, useState } from "react";
import { toast } from "sonner";
import { EcosystemFooter, EcosystemHeader } from "@/components/community/EcosystemHeader";
import { VoiceTextarea } from "@/components/community/VoiceTextarea";
import { supabase } from "@/integrations/supabase/client";
import type { Tables } from "@/integrations/supabase/database";

export const Route = createFileRoute("/event-edit/$submissionId")({ component: EditEventPage });
type Submission = Tables<"community_event_submissions">;
const editableStatuses = ["draft", "needs_information", "changes_requested", "pending_review"];

function EditEventPage() {
  const { submissionId } = Route.useParams();
  const [item, setItem] = useState<Submission | null>(null);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  useEffect(() => { void supabase.from("community_event_submissions").select("*").eq("id", submissionId).maybeSingle().then(({ data, error }) => { if (error) toast.error(error.message); setItem(data); setLoading(false); }); }, [submissionId]);
  const field = (key: keyof Submission, value: string) => setItem((current) => current ? { ...current, [key]: value } : current);
  async function save(event: FormEvent) { event.preventDefault(); if (!item) return; setSaving(true); const { error } = await supabase.from("community_event_submissions").update({ title: item.title, description: item.description, event_date: item.event_date, start_time: item.start_time, venue_name: item.venue_name, address: item.address, city: item.city, price_info: item.price_info, category: item.category, contact_info: item.contact_info, ticket_url: item.ticket_url, status: "pending_review", moderation_notes: null, updated_at: new Date().toISOString() }).eq("id", item.id); setSaving(false); if (error) return toast.error(error.message); toast.success("Evento atualizado e reenviado para revisão."); window.location.href = "/my-events"; }
  if (loading) return <div className="grid min-h-screen place-items-center bg-[#fffaf3]"><Loader2 className="size-8 animate-spin text-[#9f3d25]"/></div>;
  if (!item || !editableStatuses.includes(item.status)) return <div className="min-h-screen bg-[#fffaf3] text-[#351810]"><EcosystemHeader/><main className="mx-auto max-w-3xl px-4 py-20 text-center"><h1 className="text-3xl font-black">Este evento não pode ser editado</h1><p className="mt-2 text-[#755348]">Ele pode já ter sido aprovado, publicado ou removido.</p><Link to="/my-events" className="mt-5 inline-block font-bold text-[#9f3d25]">Voltar aos meus eventos</Link></main></div>;
  return <div className="min-h-screen bg-[#fffaf3] text-[#351810]"><EcosystemHeader/><main className="mx-auto max-w-4xl px-4 py-10"><Link to="/my-events" className="inline-flex items-center gap-2 font-bold text-[#9f3d25]"><ArrowLeft className="size-4"/>Meus eventos</Link><h1 className="mt-5 text-4xl font-black">Editar evento</h1>{item.moderation_notes ? <div className="mt-5 rounded-2xl bg-rose-50 p-4 text-rose-900"><strong>O que precisa ser ajustado</strong><p className="mt-1">{item.moderation_notes}</p></div> : null}
    <form onSubmit={(event) => void save(event)} className="mt-7 space-y-5 rounded-[2rem] border bg-white p-6 shadow-xl md:p-9"><label className="block font-semibold">Nome do evento<input required value={item.title || ""} onChange={(e) => field("title", e.target.value)} className="mt-2 h-12 w-full rounded-xl border px-4"/></label><label className="block font-semibold">Descrição<div className="mt-2"><VoiceTextarea value={item.description || ""} onChange={(value) => field("description", value)} rows={5}/></div></label><div className="grid gap-4 md:grid-cols-2">
      <label className="font-semibold">Data<input required type="date" value={item.event_date || ""} onChange={(e) => field("event_date", e.target.value)} className="mt-2 h-12 w-full rounded-xl border px-4"/></label><label className="font-semibold">Horário<input type="time" value={item.start_time || ""} onChange={(e) => field("start_time", e.target.value)} className="mt-2 h-12 w-full rounded-xl border px-4"/></label><label className="font-semibold">Local<input value={item.venue_name || ""} onChange={(e) => field("venue_name", e.target.value)} className="mt-2 h-12 w-full rounded-xl border px-4"/></label><label className="font-semibold">Cidade<input required value={item.city || ""} onChange={(e) => field("city", e.target.value)} className="mt-2 h-12 w-full rounded-xl border px-4"/></label><label className="font-semibold">Endereço<input value={item.address || ""} onChange={(e) => field("address", e.target.value)} className="mt-2 h-12 w-full rounded-xl border px-4"/></label><label className="font-semibold">Categoria<input value={item.category || ""} onChange={(e) => field("category", e.target.value)} className="mt-2 h-12 w-full rounded-xl border px-4"/></label><label className="font-semibold">Valor<input value={item.price_info || ""} onChange={(e) => field("price_info", e.target.value)} className="mt-2 h-12 w-full rounded-xl border px-4"/></label><label className="font-semibold">Contato<input value={item.contact_info || ""} onChange={(e) => field("contact_info", e.target.value)} className="mt-2 h-12 w-full rounded-xl border px-4"/></label><label className="font-semibold md:col-span-2">Link de ingresso<input value={item.ticket_url || ""} onChange={(e) => field("ticket_url", e.target.value)} className="mt-2 h-12 w-full rounded-xl border px-4"/></label></div><div className="flex gap-3 rounded-2xl bg-emerald-50 p-4 text-sm text-emerald-900"><ShieldCheck className="size-5 shrink-0"/>Ao salvar, o evento volta para a fila de revisão.</div><button disabled={saving} className="flex h-12 w-full items-center justify-center rounded-xl bg-[#9f3d25] font-bold text-white disabled:opacity-50">{saving ? <Loader2 className="size-5 animate-spin"/> : "Salvar e reenviar para revisão"}</button></form>
  </main><EcosystemFooter/></div>;
}
