import { createFileRoute, Link } from "@tanstack/react-router";
import { MapPin, Search, ShoppingBag, Wrench } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { EcosystemFooter,EcosystemHeader } from "@/components/community/EcosystemHeader";
import { supabase } from "@/integrations/supabase/client";
import type { Tables } from "@/integrations/supabase/database";
export const Route=createFileRoute("/marketplace")({component:MarketplacePage});
type Listing=Tables<"marketplace_listings">;
function MarketplacePage(){
 const [items,setItems]=useState<Listing[]>([]),[query,setQuery]=useState("");
 useEffect(()=>{supabase.from("marketplace_listings").select("*").eq("status","published").order("created_at",{ascending:false}).then(({data})=>setItems(data||[]));},[]);
 const visible=useMemo(()=>items.filter(i=>[i.title,i.description,i.category,i.city].join(" ").toLowerCase().includes(query.toLowerCase())),[items,query]);
 return <div className="min-h-screen bg-[#fffaf3] text-[#351810]"><EcosystemHeader/><main><section className="bg-[#d86132] px-4 py-14 text-white"><div className="mx-auto max-w-7xl"><div className="grid gap-8 lg:grid-cols-[1fr_.75fr]"><div><span className="inline-flex gap-2 rounded-full bg-white/15 px-3 py-1 text-sm"><ShoppingBag className="size-4"/>Economia criativa local</span><h1 className="mt-5 text-4xl font-black md:text-6xl">Descubra, valorize e contrate quem cria.</h1></div><div className="rounded-3xl bg-[#351810] p-6"><Wrench className="text-[#ffc857]"/><h2 className="mt-3 text-2xl font-black">Ferramentas Inimigos do Fim</h2><p className="mt-2 text-[#f1d5c7]">Produtos e soluções oficiais ficam em uma vitrine separada.</p><Link to="/tools" className="mt-4 inline-block font-bold text-[#ffc857]">Conhecer ferramentas →</Link></div></div><div className="mt-8 flex max-w-3xl gap-3 rounded-2xl bg-white p-3 text-[#351810]"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} className="flex-1 outline-none" placeholder="O que você procura?"/></div></div></section><section className="mx-auto max-w-7xl px-4 py-12 lg:px-8"><div className="flex items-end justify-between gap-4"><h2 className="text-3xl font-black">Feito pela comunidade</h2><Link to="/marketplace-new" className="rounded-xl border border-[#9f3d25] px-4 py-2 text-sm font-bold text-[#9f3d25]">Divulgar meu trabalho</Link></div><div className="mt-7 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{visible.map(item=><article key={item.id} className="overflow-hidden rounded-3xl border bg-white shadow-sm">{item.cover_url&&<img src={item.cover_url} alt="" className="aspect-video w-full object-cover"/>}<div className="p-6"><span className="text-xs font-bold uppercase text-[#9f3d25]">{item.category||item.listing_type}</span><h3 className="mt-2 text-xl font-black">{item.title}</h3><p className="mt-2 line-clamp-3 text-[#755348]">{item.description}</p>{item.price_label&&<strong className="mt-4 block">{item.price_label}</strong>}{item.city&&<p className="mt-2 flex gap-2 text-sm"><MapPin className="size-4"/>{item.city}</p>}{item.contact_url&&<a href={item.contact_url} target="_blank" rel="noreferrer" className="mt-5 block rounded-xl bg-[#9f3d25] px-4 py-2 text-center font-bold text-white">Tenho interesse</a>}</div></article>)}{!visible.length&&<div className="rounded-3xl border-2 border-dashed p-8 text-center md:col-span-2 lg:col-span-3"><h3 className="text-2xl font-black">A vitrine está recebendo seus primeiros trabalhos</h3><Link to="/marketplace-new" className="mt-5 inline-block rounded-xl bg-[#9f3d25] px-5 py-3 font-bold text-white">Publicar o primeiro anúncio</Link></div>}</div></section></main><EcosystemFooter/></div>;
}