import { createFileRoute } from "@tanstack/react-router";
import { Loader2, Store } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { EcosystemHeader } from "@/components/community/EcosystemHeader";
import { VoiceTextarea } from "@/components/community/VoiceTextarea";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";

export const Route=createFileRoute("/marketplace-new")({component:NewListing});
function NewListing(){
 const [userId,setUserId]=useState(""),[loading,setLoading]=useState(false);
 const [form,setForm]=useState({listing_type:"service",title:"",description:"",category:"",price_label:"",city:"",contact_url:""});
 useEffect(()=>{supabase.auth.getUser().then(({data})=>{if(!data.user)window.location.href="/join";else setUserId(data.user.id);});},[]);
 async function submit(e:FormEvent){e.preventDefault();setLoading(true);const db=supabase as unknown as {from:(table:string)=>{insert:(data:Record<string,unknown>)=>Promise<{error:{message:string}|null}>}};const {error}=await db.from("marketplace_listings").insert({...form,owner_id:userId,status:"pending"});setLoading(false);if(error){toast.error(error.message);return;}toast.success("Seu anúncio foi enviado para revisão.");window.location.href="/marketplace";}
 const field=(key:keyof typeof form,value:string)=>setForm({...form,[key]:value});
 return <div className="min-h-screen bg-[#fffaf3] text-[#351810]"><EcosystemHeader/><main className="mx-auto max-w-3xl px-4 py-10"><div className="text-center"><Store className="mx-auto size-10 text-[#9f3d25]"/><h1 className="mt-3 text-4xl font-black">Divulgue seu trabalho</h1><p className="mt-2 text-[#755348]">O anúncio será revisado antes de aparecer no marketplace.</p></div><form onSubmit={submit} className="mt-8 space-y-5 rounded-[2rem] border bg-white p-6 shadow-xl md:p-9"><label className="block font-semibold">O que você oferece?<select value={form.listing_type} onChange={e=>field("listing_type",e.target.value)} className="mt-2 h-12 w-full rounded-xl border bg-white px-3"><option value="product">Produto</option><option value="service">Serviço</option><option value="class">Aula ou oficina</option><option value="experience">Experiência</option></select></label><label className="block font-semibold">Título<input required value={form.title} onChange={e=>field("title",e.target.value)} className="mt-2 h-12 w-full rounded-xl border px-4" placeholder="Ex.: Fotografia para eventos culturais"/></label><label className="block font-semibold">Conte sobre seu trabalho<div className="mt-2"><VoiceTextarea value={form.description} onChange={v=>field("description",v)} placeholder="Fale ou digite: o que você oferece e como funciona?" rows={6}/></div></label><div className="grid gap-4 md:grid-cols-2"><label className="font-semibold">Categoria<input required value={form.category} onChange={e=>field("category",e.target.value)} className="mt-2 h-12 w-full rounded-xl border px-4" placeholder="Fotografia, artesanato..."/></label><label className="font-semibold">Valor<input value={form.price_label} onChange={e=>field("price_label",e.target.value)} className="mt-2 h-12 w-full rounded-xl border px-4" placeholder="R$ 100, sob consulta..."/></label><label className="font-semibold">Cidade<input value={form.city} onChange={e=>field("city",e.target.value)} className="mt-2 h-12 w-full rounded-xl border px-4"/></label><label className="font-semibold">Link para contato<input value={form.contact_url} onChange={e=>field("contact_url",e.target.value)} className="mt-2 h-12 w-full rounded-xl border px-4" placeholder="WhatsApp, Instagram ou site"/></label></div><button disabled={loading||!userId} className="flex h-12 w-full items-center justify-center rounded-xl bg-[#9f3d25] font-bold text-white disabled:opacity-50">{loading?<Loader2 className="size-5 animate-spin"/>:"Enviar para revisão"}</button></form></main></div>;
}
