import { createFileRoute, Link } from "@tanstack/react-router";
import { BriefcaseBusiness, Package, Search, ShoppingBag, Sparkles, Wrench } from "lucide-react";
import { EcosystemFooter, EcosystemHeader } from "@/components/community/EcosystemHeader";

export const Route = createFileRoute("/marketplace")({ component: MarketplacePage });

const categories = [
  { title: "Arte e artesanato", text: "Peças autorais, decoração, moda e presentes.", icon: Package },
  { title: "Serviços criativos", text: "Design, foto, vídeo, comunicação e produção.", icon: BriefcaseBusiness },
  { title: "Aulas e experiências", text: "Oficinas, cursos, apresentações e vivências.", icon: Sparkles },
];

function MarketplacePage() {
  return <div className="min-h-screen bg-[#fffaf3] text-[#351810]"><EcosystemHeader /><main><section className="bg-[#d86132] px-4 py-14 text-white"><div className="mx-auto max-w-7xl"><div className="grid gap-8 lg:grid-cols-[1fr_.75fr] lg:items-end"><div><span className="inline-flex items-center gap-2 rounded-full bg-white/15 px-3 py-1 text-sm"><ShoppingBag className="size-4" /> Economia criativa local</span><h1 className="mt-5 max-w-3xl text-4xl font-black md:text-6xl">Descubra, valorize e contrate quem cria.</h1><p className="mt-4 max-w-2xl text-lg text-orange-50">Produtos, serviços, aulas e experiências publicados por pessoas da comunidade.</p></div><div className="rounded-3xl bg-[#351810] p-6"><Wrench className="size-7 text-[#ffc857]" /><h2 className="mt-3 text-2xl font-black">Ferramentas Inimigos do Fim</h2><p className="mt-2 text-[#f1d5c7]">Uma área exclusiva para recursos, materiais digitais e soluções selecionadas pela plataforma.</p><Link to="/tools" className="mt-5 inline-block rounded-xl bg-[#ffc857] px-4 py-2 font-bold text-[#351810]">Conhecer ferramentas</Link></div></div><div className="mt-9 flex max-w-3xl items-center gap-3 rounded-2xl bg-white p-3 text-[#351810] shadow-xl"><Search className="size-5 text-[#d86132]" /><input className="min-w-0 flex-1 bg-transparent outline-none" placeholder="O que você procura?" /><button className="rounded-xl bg-[#9f3d25] px-5 py-2 font-semibold text-white">Buscar</button></div></div></section><section className="mx-auto max-w-7xl px-4 py-12 lg:px-8"><div className="flex items-end justify-between"><div><p className="font-bold uppercase tracking-widest text-[#9f3d25]">Explore</p><h2 className="mt-2 text-3xl font-black">Feito pela comunidade</h2></div><Link to="/marketplace-new" className="rounded-xl border border-[#9f3d25] px-4 py-2 text-sm font-bold text-[#9f3d25]">Quero divulgar meu trabalho</Link></div><div className="mt-7 grid gap-5 md:grid-cols-3">{categories.map(({title,text,icon:Icon})=><article key={title} className="rounded-3xl border border-[#ead9ca] bg-white p-6 shadow-sm"><span className="grid size-12 place-items-center rounded-2xl bg-[#f4e6d7] text-[#9f3d25]"><Icon /></span><h3 className="mt-5 text-xl font-bold">{title}</h3><p className="mt-2 text-[#755348]">{text}</p><button className="mt-5 font-bold text-[#9f3d25]">Explorar →</button></article>)}</div><div className="mt-10 rounded-3xl border-2 border-dashed border-[#d6b8a5] p-8 text-center"><h2 className="text-2xl font-black">A vitrine está sendo preparada</h2><p className="mx-auto mt-2 max-w-2xl text-[#755348]">Os anúncios terão página própria, galeria, descrição assistida, localização, contato e vínculo com o perfil cultural de quem oferece.</p></div></section></main><EcosystemFooter /></div>;
}
