import { createFileRoute, Link } from "@tanstack/react-router";
import { MapPin, Mic, Search, Sparkles } from "lucide-react";
import { EcosystemFooter, EcosystemHeader } from "@/components/community/EcosystemHeader";

export const Route = createFileRoute("/people")({ component: PeoplePage });

const categories = ["Todas as áreas", "Música", "Artes visuais", "Produção cultural", "Artesanato", "Espaços", "Serviços"];

function PeoplePage() {
  return <div className="min-h-screen bg-[#fffaf3] text-[#351810]"><EcosystemHeader /><main className="mx-auto max-w-7xl px-4 py-10 lg:px-8"><section className="rounded-[2rem] bg-[#351810] p-7 text-white md:p-12"><p className="font-bold uppercase tracking-widest text-[#ffc857]">Mapa humano da cultura</p><h1 className="mt-3 max-w-3xl text-4xl font-black md:text-5xl">Encontre quem faz a cultura acontecer.</h1><p className="mt-4 max-w-2xl text-[#f1d5c7]">Descubra artistas, coletivos, espaços e profissionais para acompanhar, contratar ou criar junto.</p><div className="mt-7 flex max-w-3xl items-center gap-3 rounded-2xl bg-white p-3 text-[#351810]"><Search className="size-5 text-[#9f3d25]" /><input className="min-w-0 flex-1 bg-transparent outline-none" placeholder="Busque por nome, trabalho, cidade ou habilidade" /><button className="rounded-xl bg-[#9f3d25] px-4 py-2 font-semibold text-white">Buscar</button></div></section><div className="mt-8 flex gap-2 overflow-x-auto pb-2">{categories.map((category,index)=><button key={category} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm font-semibold ${index===0?"bg-[#9f3d25] text-white":"border border-[#dfc7b7] bg-white"}`}>{category}</button>)}</div><section className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3"><div className="rounded-3xl border-2 border-dashed border-[#d6b8a5] bg-white/60 p-7 md:col-span-2 lg:col-span-3"><div className="mx-auto max-w-xl text-center"><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-[#f4e6d7] text-[#9f3d25]"><Sparkles /></span><h2 className="mt-4 text-2xl font-black">Os primeiros perfis vão aparecer aqui</h2><p className="mt-2 text-[#755348]">Você não precisa saber escrever uma bio. Conte sua história falando ou digitando e a assistente organiza seu portfólio.</p><Link to="/join" className="mt-5 inline-flex items-center gap-2 rounded-xl bg-[#9f3d25] px-5 py-3 font-bold text-white"><Mic className="size-4" /> Criar perfil com ajuda</Link></div></div></section><section className="mt-10 grid gap-4 sm:grid-cols-3">{["Pessoas perto de você","Trabalhos que combinam","Disponíveis para colaborar"].map(label=><div key={label} className="rounded-2xl bg-[#f4e6d7] p-5"><MapPin className="size-5 text-[#9f3d25]" /><strong className="mt-3 block">{label}</strong><p className="mt-1 text-sm text-[#755348]">Recomendações personalizadas quando você completar seu perfil.</p></div>)}</section></main><EcosystemFooter /></div>;
}
