import { createFileRoute } from "@tanstack/react-router";
import { ExternalLink, Loader2, Plus, Wrench } from "lucide-react";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { DashboardLayout } from "@/components/layout/DashboardLayout";
import { supabase } from "@/integrations/supabase/client";
import type { Tables } from "@/integrations/supabase/database";
import { toast } from "sonner";
export const Route=createFileRoute("/tool-management")({component:ToolManagement});
type Tool=Tables<"platform_tools">;
function ToolManagement(){
 const [tools,setTools]=useState<Tool[]>([]),[saving,setSaving]=useState(false);
 const [form,setForm]=useState({title:"",slug:"",short_description:"",sales_url:"",price_label:"",status:"draft"});
 const load=useCallback(()=>{supabase.from("platform_tools").select("*").order("sort_order",{ascending:true}).then(({data})=>setTools(data||[]));},[]);
 useEffect(()=>{load();},[load]);
 async function create(e:FormEvent){e.preventDefault();setSaving(true);const {error}=await supabase.from("platform_tools").insert({...form,slug:form.slug||form.title.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")});setSaving(false);if(error){toast.error(error.message);return;}toast.success("Ferramenta cadastrada.");setForm({title:"",slug:"",short_description:"",sales_url:"",price_label:"",status:"draft"});load();}
 async function toggle(tool:Tool){const next=tool.status==="published"?"paused":"published";const {error}=await supabase.from("platform_tools").update({status:next,updated_at:new Date().toISOString()}).eq("id",tool.id);if(error)toast.error(error.message);else{toast.success(next==="published"?"Ferramenta publicada.":"Ferramenta pausada.");load();}}
 return <DashboardLayout><div className="space-y-7"><div><h1 className="text-2xl font-bold">Ferramentas e materiais</h1><p className="text-muted-foreground">Gerencie a vitrine oficial de produtos do Inimigos do Fim.</p></div><form onSubmit={create} className="grid gap-4 rounded-xl border bg-card p-5 md:grid-cols-2"><h2 className="flex items-center gap-2 text-lg font-bold md:col-span-2"><Plus className="size-5"/>Nova ferramenta</h2><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className="h-11 rounded-lg border px-3" placeholder="Nome da ferramenta"/><input value={form.price_label} onChange={e=>setForm({...form,price_label:e.target.value})} className="h-11 rounded-lg border px-3" placeholder="Preço ou condição"/><textarea required value={form.short_description} onChange={e=>setForm({...form,short_description:e.target.value})} className="rounded-lg border p-3 md:col-span-2" placeholder="Descrição curta"/><input required type="url" value={form.sales_url} onChange={e=>setForm({...form,sales_url:e.target.value})} className="h-11 rounded-lg border px-3 md:col-span-2" placeholder="Página de vendas ou checkout"/><button disabled={saving} className="h-11 rounded-lg bg-primary font-semibold text-primary-foreground md:col-span-2">{saving?<Loader2 className="mx-auto size-5 animate-spin"/>:"Salvar ferramenta"}</button></form><section><h2 className="mb-4 text-lg font-bold">Vitrine cadastrada</h2><div className="grid gap-4 md:grid-cols-2">{tools.map(tool=><article key={tool.id} className="rounded-xl border bg-card p-5"><div className="flex justify-between gap-4"><div><span className="text-xs font-bold uppercase text-muted-foreground">{tool.status}</span><h3 className="mt-1 text-lg font-bold">{tool.title}</h3><p className="mt-2 text-sm text-muted-foreground">{tool.short_description}</p><strong className="mt-3 block text-sm">{tool.price_label}</strong></div><Wrench className="size-6 text-primary"/></div><div className="mt-4 flex gap-2"><button onClick={()=>toggle(tool)} className="flex-1 rounded-lg bg-primary py-2 text-sm font-semibold text-primary-foreground">{tool.status==="published"?"Pausar":"Publicar"}</button>{tool.sales_url&&<a href={tool.sales_url} target="_blank" rel="noreferrer" className="grid size-10 place-items-center rounded-lg border"><ExternalLink className="size-4"/></a>}</div></article>)}{!tools.length&&<p className="rounded-xl border border-dashed p-6 text-center text-muted-foreground md:col-span-2">Nenhuma ferramenta cadastrada.</p>}</div></section></div></DashboardLayout>;
}
