import { createFileRoute } from "@tanstack/react-router";
import { ArrowRight, Sparkles, Wrench } from "lucide-react";
import { useEffect, useState } from "react";
import { EcosystemFooter,EcosystemHeader } from "@/components/community/EcosystemHeader";
import { supabase } from "@/integrations/supabase/client";
export const Route=createFileRoute("/tools")({component:ToolsPage});
type Tool={id:string;title:string;short_description:string|null;cover_url:string|null;sales_url:string|null;price_label:string|null;benefits:string[];is_featured:boolean};
function ToolsPage(){
 const [items,setItems]=useState<Tool[]>([]);
 useEffect(()=>{const db=supabase as unknown as {from:(t:string)=>{select:(s:string)=>{eq:(k:string,v:string)=>{order:(k:string,o:object)=>Promise<{data:Tool[]|null}>}}}};db.from("platform_tools").select("*").eq("status","published").order("sort_order",{ascending:true}).then(({data})=>setItems(data||[]));},[]);
 return <div className="min-h-screen bg-[#fffaf3] text-[#351810]"><EcosystemHeader/><main><section className="bg-[#351810] px-4 py-16 text-white"><div className="mx-auto max-w-7xl"><span className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1 text-sm text-[#ffd99b]"><Sparkles className="size-4"/>Curadoria Inimigos do Fim</span><h1 className="mt-5 max-w-4xl text-4xl font-black md:text-6xl">Ferramentas para transformar ideias em projetos reais.</h1><p className="mt-5 max-w-2xl text-lg text-[#f1d5c7]">Materiais e soluções oficiais para criação, divulgação, organização e vendas.</p></div></section><section className="mx-auto max-w-7xl px-4 py-12 lg:px-8"><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{items.map(item=><article key={item.id} className={`overflow-hidden rounded-3xl border bg-white shadow-sm ${item.is_featured?"ring-2 ring-[#d86132]":""}`}>{item.cover_url?<img src={item.cover_url} alt="" className="aspect-video w-full object-cover"/>:<div className="grid aspect-video place-items-center bg-[#f4e6d7]"><Wrench className="size-12 text-[#9f3d25]"/></div>}<div className="p-6">{item.is_featured&&<span className="text-xs font-bold uppercase text-[#d86132]">Destaque</span>}<h2 className="mt-2 text-2xl font-black">{item.title}</h2><p className="mt-3 text-[#755348]">{item.short_description}</p>{item.price_label&&<strong className="mt-4 block text-lg">{item.price_label}</strong>}{item.sales_url&&<a href={item.sales_url} target="_blank" rel="noreferrer" className="mt-5 flex items-center justify-center gap-2 rounded-xl bg-[#9f3d25] px-4 py-3 font-bold text-white">Conhecer ferramenta<ArrowRight className="size-4"/></a>}</div></article>)}{!items.length&&<div className="rounded-[2rem] bg-[#f4e6d7] p-10 text-center md:col-span-2 lg:col-span-3"><h2 className="text-3xl font-black">A vitrine está sendo preparada</h2><p className="mt-3 text-[#755348]">As primeiras ferramentas e materiais aparecerão aqui assim que forem publicados.</p></div>}</div></section></main><EcosystemFooter/></div>;
}