import { Ban, BellOff, Flag, Loader2, ShieldCheck, Volume2, X } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";

type Props = { targetProfileId: string; targetName?: string; compact?: boolean };

type SafetyClient = typeof supabase & { rpc: (fn: string, args?: Record<string, unknown>) => Promise<{ data: unknown; error: { message: string } | null }> };
const client = supabase as SafetyClient;

export function SocialSafetyControls({ targetProfileId, targetName = "este perfil", compact = false }: Props) {
  const [userId,setUserId]=useState<string|null>(null),[blocked,setBlocked]=useState(false),[muted,setMuted]=useState(false),[busy,setBusy]=useState<string|null>(null),[reporting,setReporting]=useState(false),[reason,setReason]=useState(""),[details,setDetails]=useState("");
  useEffect(()=>{let active=true;(async()=>{const{data}=await supabase.auth.getUser();const id=data.user?.id??null;if(!active)return;setUserId(id);if(!id||id===targetProfileId)return;const[b,m]=await Promise.all([supabase.from("community_profile_blocks" as never).select("blocked_id").eq("blocker_id",id).eq("blocked_id",targetProfileId).maybeSingle(),supabase.from("community_profile_mutes" as never).select("muted_id").eq("muter_id",id).eq("muted_id",targetProfileId).maybeSingle()]);if(!active)return;setBlocked(Boolean(b.data));setMuted(Boolean(m.data));})().catch(()=>{});return()=>{active=false}},[targetProfileId]);
  if(!userId||userId===targetProfileId)return null;
  async function toggleBlock(){const next=!blocked;if(next&&!window.confirm(`Bloquear ${targetName}? Vocês não poderão iniciar ou continuar conversas diretas enquanto o bloqueio estiver ativo.`))return;setBusy("block");const{error}=await client.rpc("set_profile_block",{target_profile_id:targetProfileId,should_block:next});setBusy(null);if(error){toast.error(error.message);return}setBlocked(next);if(next)setMuted(false);toast.success(next?"Perfil bloqueado.":"Perfil desbloqueado.")}
  async function toggleMute(){const next=!muted;setBusy("mute");const{error}=await client.rpc("set_profile_mute",{target_profile_id:targetProfileId,should_mute:next});setBusy(null);if(error){toast.error(error.message);return}setMuted(next);toast.success(next?"Notificações deste perfil foram silenciadas.":"Notificações deste perfil foram reativadas.")}
  async function submitReport(){if(reason.trim().length<3){toast.error("Informe o motivo da denúncia.");return}setBusy("report");const{error}=await client.rpc("submit_community_report",{target_type:"profile",target_id:targetProfileId,report_reason:reason.trim(),report_details:details.trim()||null});setBusy(null);if(error){toast.error(error.message);return}setReporting(false);setReason("");setDetails("");toast.success("Denúncia enviada para análise da moderação.")}
  return <div className={compact?"flex flex-wrap gap-2":"mt-4 flex flex-wrap gap-2"}>
    <button type="button" disabled={busy!==null} onClick={()=>void toggleMute()} className="inline-flex items-center gap-2 rounded-xl border border-white/25 px-3 py-2 text-sm font-bold text-white/90 hover:bg-white/10 disabled:opacity-50">{busy==="mute"?<Loader2 className="size-4 animate-spin"/>:muted?<Volume2 className="size-4"/>:<BellOff className="size-4"/>}{muted?"Reativar alertas":"Silenciar"}</button>
    <button type="button" disabled={busy!==null} onClick={()=>void toggleBlock()} className="inline-flex items-center gap-2 rounded-xl border border-white/25 px-3 py-2 text-sm font-bold text-white/90 hover:bg-white/10 disabled:opacity-50">{busy==="block"?<Loader2 className="size-4 animate-spin"/>:blocked?<ShieldCheck className="size-4"/>:<Ban className="size-4"/>}{blocked?"Desbloquear":"Bloquear"}</button>
    <button type="button" disabled={busy!==null} onClick={()=>setReporting(true)} className="inline-flex items-center gap-2 rounded-xl border border-white/25 px-3 py-2 text-sm font-bold text-white/90 hover:bg-white/10 disabled:opacity-50"><Flag className="size-4"/>Denunciar</button>
    {reporting?<div className="fixed inset-0 z-[80] grid place-items-center bg-black/55 p-4" role="dialog" aria-modal="true" aria-label="Denunciar perfil"><div className="w-full max-w-lg rounded-3xl bg-[#fffaf3] p-6 text-[#351810] shadow-2xl"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-black uppercase tracking-widest text-[#9f3d25]">Segurança</p><h2 className="mt-1 text-2xl font-black">Denunciar {targetName}</h2></div><button type="button" onClick={()=>setReporting(false)} className="rounded-xl p-2 hover:bg-[#f4e6d7]" aria-label="Fechar"><X className="size-5"/></button></div><p className="mt-3 text-sm text-[#755348]">A denúncia será enviada para a moderação. A pessoa denunciada não recebe sua identidade por este formulário.</p><label className="mt-5 block text-sm font-bold">Motivo<input value={reason} maxLength={120} onChange={e=>setReason(e.target.value)} className="mt-2 w-full rounded-xl border border-[#ead9ca] bg-white px-4 py-3 font-normal outline-none focus:border-[#9f3d25]" placeholder="Ex.: assédio, spam, conteúdo inadequado"/></label><label className="mt-4 block text-sm font-bold">Detalhes opcionais<textarea value={details} maxLength={1500} onChange={e=>setDetails(e.target.value)} rows={4} className="mt-2 w-full resize-none rounded-xl border border-[#ead9ca] bg-white px-4 py-3 font-normal outline-none focus:border-[#9f3d25]" placeholder="Conte o que aconteceu para ajudar na análise."/></label><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={()=>setReporting(false)} className="rounded-xl px-4 py-2.5 font-bold text-[#755348]">Cancelar</button><button type="button" disabled={busy!==null||reason.trim().length<3} onClick={()=>void submitReport()} className="inline-flex items-center gap-2 rounded-xl bg-[#9f3d25] px-4 py-2.5 font-bold text-white disabled:opacity-40">{busy==="report"?<Loader2 className="size-4 animate-spin"/>:<Flag className="size-4"/>}Enviar denúncia</button></div></div></div>:null}
  </div>
}