/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CommunityModerationRouteImport } from './routes/community-moderation'
import { Route as FeedsRouteImport } from './routes/feeds'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as HealthRouteImport } from './routes/health'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as InterpretedRouteImport } from './routes/interpreted'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as MarketplaceNewRouteImport } from './routes/marketplace-new'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MyEventsRouteImport } from './routes/my-events'
import { Route as MyListingsRouteImport } from './routes/my-listings'
import { Route as MyProfileRouteImport } from './routes/my-profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as PublishedRouteImport } from './routes/published'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SubmitEventRouteImport } from './routes/submit-event'
import { Route as ToolManagementRouteImport } from './routes/tool-management'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as ChatsRoomIdRouteImport } from './routes/chats.$roomId'
import { Route as CommunitySpaceSlugRouteImport } from './routes/community.$spaceSlug'
import { Route as EventEditSubmissionIdRouteImport } from './routes/event-edit.$submissionId'
import { Route as MarketplaceEditListingIdRouteImport } from './routes/marketplace-edit.$listingId'
import { Route as MarketplaceListingIdRouteImport } from './routes/marketplace.$listingId'
import { Route as PeopleProfileIdRouteImport } from './routes/people.$profileId'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicEventsRouteImport } from './routes/api/public/events'
import { Route as ApiPublicMaintenanceRouteImport } from './routes/api/public/maintenance'
import { Route as ApiPublicSyncFeedsRouteImport } from './routes/api/public/sync-feeds'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityModerationRoute = CommunityModerationRouteImport.update({
  id: '/community-moderation',
  path: '/community-moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedsRoute = FeedsRouteImport.update({
  id: '/feeds',
  path: '/feeds',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const InterpretedRoute = InterpretedRouteImport.update({
  id: '/interpreted',
  path: '/interpreted',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceNewRoute = MarketplaceNewRouteImport.update({
  id: '/marketplace-new',
  path: '/marketplace-new',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MyEventsRoute = MyEventsRouteImport.update({
  id: '/my-events',
  path: '/my-events',
  getParentRoute: () => rootRouteImport,
} as any)
const MyListingsRoute = MyListingsRouteImport.update({
  id: '/my-listings',
  path: '/my-listings',
  getParentRoute: () => rootRouteImport,
} as any)
const MyProfileRoute = MyProfileRouteImport.update({
  id: '/my-profile',
  path: '/my-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishedRoute = PublishedRouteImport.update({
  id: '/published',
  path: '/published',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitEventRoute = SubmitEventRouteImport.update({
  id: '/submit-event',
  path: '/submit-event',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolManagementRoute = ToolManagementRouteImport.update({
  id: '/tool-management',
  path: '/tool-management',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const ChatsRoomIdRoute = ChatsRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => ChatsRoute,
} as any)
const CommunitySpaceSlugRoute = CommunitySpaceSlugRouteImport.update({
  id: '/$spaceSlug',
  path: '/$spaceSlug',
  getParentRoute: () => CommunityRoute,
} as any)
const EventEditSubmissionIdRoute = EventEditSubmissionIdRouteImport.update({
  id: '/event-edit/$submissionId',
  path: '/event-edit/$submissionId',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceEditListingIdRoute =
  MarketplaceEditListingIdRouteImport.update({
    id: '/marketplace-edit/$listingId',
    path: '/marketplace-edit/$listingId',
    getParentRoute: () => rootRouteImport,
  } as any)
const MarketplaceListingIdRoute = MarketplaceListingIdRouteImport.update({
  id: '/$listingId',
  path: '/$listingId',
  getParentRoute: () => MarketplaceRoute,
} as any)
const PeopleProfileIdRoute = PeopleProfileIdRouteImport.update({
  id: '/$profileId',
  path: '/$profileId',
  getParentRoute: () => PeopleRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEventsRoute = ApiPublicEventsRouteImport.update({
  id: '/api/public/events',
  path: '/api/public/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMaintenanceRoute = ApiPublicMaintenanceRouteImport.update({
  id: '/api/public/maintenance',
  path: '/api/public/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncFeedsRoute = ApiPublicSyncFeedsRouteImport.update({
  id: '/api/public/sync-feeds',
  path: '/api/public/sync-feeds',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp-webhook',
    path: '/api/public/whatsapp-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/chats': typeof ChatsRouteWithChildren
  '/community': typeof CommunityRouteWithChildren
  '/community-moderation': typeof CommunityModerationRoute
  '/feeds': typeof FeedsRoute
  '/groups': typeof GroupsRoute
  '/health': typeof HealthRoute
  '/inbox': typeof InboxRoute
  '/integrations': typeof IntegrationsRoute
  '/interpreted': typeof InterpretedRoute
  '/join': typeof JoinRoute
  '/logs': typeof LogsRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/marketplace-new': typeof MarketplaceNewRoute
  '/mcp': typeof McpRoute
  '/my-events': typeof MyEventsRoute
  '/my-listings': typeof MyListingsRoute
  '/my-profile': typeof MyProfileRoute
  '/notifications': typeof NotificationsRoute
  '/people': typeof PeopleRouteWithChildren
  '/published': typeof PublishedRoute
  '/review': typeof ReviewRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/submit-event': typeof SubmitEventRoute
  '/tool-management': typeof ToolManagementRoute
  '/tools': typeof ToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/chats/$roomId': typeof ChatsRoomIdRoute
  '/community/$spaceSlug': typeof CommunitySpaceSlugRoute
  '/event-edit/$submissionId': typeof EventEditSubmissionIdRoute
  '/marketplace-edit/$listingId': typeof MarketplaceEditListingIdRoute
  '/marketplace/$listingId': typeof MarketplaceListingIdRoute
  '/people/$profileId': typeof PeopleProfileIdRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/events': typeof ApiPublicEventsRoute
  '/api/public/maintenance': typeof ApiPublicMaintenanceRoute
  '/api/public/sync-feeds': typeof ApiPublicSyncFeedsRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/chats': typeof ChatsRouteWithChildren
  '/community': typeof CommunityRouteWithChildren
  '/community-moderation': typeof CommunityModerationRoute
  '/feeds': typeof FeedsRoute
  '/groups': typeof GroupsRoute
  '/health': typeof HealthRoute
  '/inbox': typeof InboxRoute
  '/integrations': typeof IntegrationsRoute
  '/interpreted': typeof InterpretedRoute
  '/join': typeof JoinRoute
  '/logs': typeof LogsRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/marketplace-new': typeof MarketplaceNewRoute
  '/mcp': typeof McpRoute
  '/my-events': typeof MyEventsRoute
  '/my-listings': typeof MyListingsRoute
  '/my-profile': typeof MyProfileRoute
  '/notifications': typeof NotificationsRoute
  '/people': typeof PeopleRouteWithChildren
  '/published': typeof PublishedRoute
  '/review': typeof ReviewRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/submit-event': typeof SubmitEventRoute
  '/tool-management': typeof ToolManagementRoute
  '/tools': typeof ToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/chats/$roomId': typeof ChatsRoomIdRoute
  '/community/$spaceSlug': typeof CommunitySpaceSlugRoute
  '/event-edit/$submissionId': typeof EventEditSubmissionIdRoute
  '/marketplace-edit/$listingId': typeof MarketplaceEditListingIdRoute
  '/marketplace/$listingId': typeof MarketplaceListingIdRoute
  '/people/$profileId': typeof PeopleProfileIdRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/events': typeof ApiPublicEventsRoute
  '/api/public/maintenance': typeof ApiPublicMaintenanceRoute
  '/api/public/sync-feeds': typeof ApiPublicSyncFeedsRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/chats': typeof ChatsRouteWithChildren
  '/community': typeof CommunityRouteWithChildren
  '/community-moderation': typeof CommunityModerationRoute
  '/feeds': typeof FeedsRoute
  '/groups': typeof GroupsRoute
  '/health': typeof HealthRoute
  '/inbox': typeof InboxRoute
  '/integrations': typeof IntegrationsRoute
  '/interpreted': typeof InterpretedRoute
  '/join': typeof JoinRoute
  '/logs': typeof LogsRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/marketplace-new': typeof MarketplaceNewRoute
  '/mcp': typeof McpRoute
  '/my-events': typeof MyEventsRoute
  '/my-listings': typeof MyListingsRoute
  '/my-profile': typeof MyProfileRoute
  '/notifications': typeof NotificationsRoute
  '/people': typeof PeopleRouteWithChildren
  '/published': typeof PublishedRoute
  '/review': typeof ReviewRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/submit-event': typeof SubmitEventRoute
  '/tool-management': typeof ToolManagementRoute
  '/tools': typeof ToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/chats/$roomId': typeof ChatsRoomIdRoute
  '/community/$spaceSlug': typeof CommunitySpaceSlugRoute
  '/event-edit/$submissionId': typeof EventEditSubmissionIdRoute
  '/marketplace-edit/$listingId': typeof MarketplaceEditListingIdRoute
  '/marketplace/$listingId': typeof MarketplaceListingIdRoute
  '/people/$profileId': typeof PeopleProfileIdRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/events': typeof ApiPublicEventsRoute
  '/api/public/maintenance': typeof ApiPublicMaintenanceRoute
  '/api/public/sync-feeds': typeof ApiPublicSyncFeedsRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/auth'
    | '/chats'
    | '/community'
    | '/community-moderation'
    | '/feeds'
    | '/groups'
    | '/health'
    | '/inbox'
    | '/integrations'
    | '/interpreted'
    | '/join'
    | '/logs'
    | '/marketplace'
    | '/marketplace-new'
    | '/mcp'
    | '/my-events'
    | '/my-listings'
    | '/my-profile'
    | '/notifications'
    | '/people'
    | '/published'
    | '/review'
    | '/rules'
    | '/settings'
    | '/submit-event'
    | '/tool-management'
    | '/tools'
    | '/.well-known/oauth-protected-resource'
    | '/chats/$roomId'
    | '/community/$spaceSlug'
    | '/event-edit/$submissionId'
    | '/marketplace-edit/$listingId'
    | '/marketplace/$listingId'
    | '/people/$profileId'
    | '/.lovable/oauth/consent'
    | '/api/public/events'
    | '/api/public/maintenance'
    | '/api/public/sync-feeds'
    | '/api/public/whatsapp-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/auth'
    | '/chats'
    | '/community'
    | '/community-moderation'
    | '/feeds'
    | '/groups'
    | '/health'
    | '/inbox'
    | '/integrations'
    | '/interpreted'
    | '/join'
    | '/logs'
    | '/marketplace'
    | '/marketplace-new'
    | '/mcp'
    | '/my-events'
    | '/my-listings'
    | '/my-profile'
    | '/notifications'
    | '/people'
    | '/published'
    | '/review'
    | '/rules'
    | '/settings'
    | '/submit-event'
    | '/tool-management'
    | '/tools'
    | '/.well-known/oauth-protected-resource'
    | '/chats/$roomId'
    | '/community/$spaceSlug'
    | '/event-edit/$submissionId'
    | '/marketplace-edit/$listingId'
    | '/marketplace/$listingId'
    | '/people/$profileId'
    | '/.lovable/oauth/consent'
    | '/api/public/events'
    | '/api/public/maintenance'
    | '/api/public/sync-feeds'
    | '/api/public/whatsapp-webhook'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/auth'
    | '/chats'
    | '/community'
    | '/community-moderation'
    | '/feeds'
    | '/groups'
    | '/health'
    | '/inbox'
    | '/integrations'
    | '/interpreted'
    | '/join'
    | '/logs'
    | '/marketplace'
    | '/marketplace-new'
    | '/mcp'
    | '/my-events'
    | '/my-listings'
    | '/my-profile'
    | '/notifications'
    | '/people'
    | '/published'
    | '/review'
    | '/rules'
    | '/settings'
    | '/submit-event'
    | '/tool-management'
    | '/tools'
    | '/.well-known/oauth-protected-resource'
    | '/chats/$roomId'
    | '/community/$spaceSlug'
    | '/event-edit/$submissionId'
    | '/marketplace-edit/$listingId'
    | '/marketplace/$listingId'
    | '/people/$profileId'
    | '/.lovable/oauth/consent'
    | '/api/public/events'
    | '/api/public/maintenance'
    | '/api/public/sync-feeds'
    | '/api/public/whatsapp-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AuthRoute: typeof AuthRoute
  ChatsRoute: typeof ChatsRouteWithChildren
  CommunityRoute: typeof CommunityRouteWithChildren
  CommunityModerationRoute: typeof CommunityModerationRoute
  FeedsRoute: typeof FeedsRoute
  GroupsRoute: typeof GroupsRoute
  HealthRoute: typeof HealthRoute
  InboxRoute: typeof InboxRoute
  IntegrationsRoute: typeof IntegrationsRoute
  InterpretedRoute: typeof InterpretedRoute
  JoinRoute: typeof JoinRoute
  LogsRoute: typeof LogsRoute
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
  MarketplaceNewRoute: typeof MarketplaceNewRoute
  McpRoute: typeof McpRoute
  MyEventsRoute: typeof MyEventsRoute
  MyListingsRoute: typeof MyListingsRoute
  MyProfileRoute: typeof MyProfileRoute
  NotificationsRoute: typeof NotificationsRoute
  PeopleRoute: typeof PeopleRouteWithChildren
  PublishedRoute: typeof PublishedRoute
  ReviewRoute: typeof ReviewRoute
  RulesRoute: typeof RulesRoute
  SettingsRoute: typeof SettingsRoute
  SubmitEventRoute: typeof SubmitEventRoute
  ToolManagementRoute: typeof ToolManagementRoute
  ToolsRoute: typeof ToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  EventEditSubmissionIdRoute: typeof EventEditSubmissionIdRoute
  MarketplaceEditListingIdRoute: typeof MarketplaceEditListingIdRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  ApiPublicEventsRoute: typeof ApiPublicEventsRoute
  ApiPublicMaintenanceRoute: typeof ApiPublicMaintenanceRoute
  ApiPublicSyncFeedsRoute: typeof ApiPublicSyncFeedsRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-moderation': {
      id: '/community-moderation'
      path: '/community-moderation'
      fullPath: '/community-moderation'
      preLoaderRoute: typeof CommunityModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feeds': {
      id: '/feeds'
      path: '/feeds'
      fullPath: '/feeds'
      preLoaderRoute: typeof FeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interpreted': {
      id: '/interpreted'
      path: '/interpreted'
      fullPath: '/interpreted'
      preLoaderRoute: typeof InterpretedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace-new': {
      id: '/marketplace-new'
      path: '/marketplace-new'
      fullPath: '/marketplace-new'
      preLoaderRoute: typeof MarketplaceNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-events': {
      id: '/my-events'
      path: '/my-events'
      fullPath: '/my-events'
      preLoaderRoute: typeof MyEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-listings': {
      id: '/my-listings'
      path: '/my-listings'
      fullPath: '/my-listings'
      preLoaderRoute: typeof MyListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-profile': {
      id: '/my-profile'
      path: '/my-profile'
      fullPath: '/my-profile'
      preLoaderRoute: typeof MyProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/published': {
      id: '/published'
      path: '/published'
      fullPath: '/published'
      preLoaderRoute: typeof PublishedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit-event': {
      id: '/submit-event'
      path: '/submit-event'
      fullPath: '/submit-event'
      preLoaderRoute: typeof SubmitEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool-management': {
      id: '/tool-management'
      path: '/tool-management'
      fullPath: '/tool-management'
      preLoaderRoute: typeof ToolManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats/$roomId': {
      id: '/chats/$roomId'
      path: '/$roomId'
      fullPath: '/chats/$roomId'
      preLoaderRoute: typeof ChatsRoomIdRouteImport
      parentRoute: typeof ChatsRoute
    }
    '/community/$spaceSlug': {
      id: '/community/$spaceSlug'
      path: '/$spaceSlug'
      fullPath: '/community/$spaceSlug'
      preLoaderRoute: typeof CommunitySpaceSlugRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/event-edit/$submissionId': {
      id: '/event-edit/$submissionId'
      path: '/event-edit/$submissionId'
      fullPath: '/event-edit/$submissionId'
      preLoaderRoute: typeof EventEditSubmissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace-edit/$listingId': {
      id: '/marketplace-edit/$listingId'
      path: '/marketplace-edit/$listingId'
      fullPath: '/marketplace-edit/$listingId'
      preLoaderRoute: typeof MarketplaceEditListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/$listingId': {
      id: '/marketplace/$listingId'
      path: '/$listingId'
      fullPath: '/marketplace/$listingId'
      preLoaderRoute: typeof MarketplaceListingIdRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/people/$profileId': {
      id: '/people/$profileId'
      path: '/$profileId'
      fullPath: '/people/$profileId'
      preLoaderRoute: typeof PeopleProfileIdRouteImport
      parentRoute: typeof PeopleRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/events': {
      id: '/api/public/events'
      path: '/api/public/events'
      fullPath: '/api/public/events'
      preLoaderRoute: typeof ApiPublicEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/maintenance': {
      id: '/api/public/maintenance'
      path: '/api/public/maintenance'
      fullPath: '/api/public/maintenance'
      preLoaderRoute: typeof ApiPublicMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-feeds': {
      id: '/api/public/sync-feeds'
      path: '/api/public/sync-feeds'
      fullPath: '/api/public/sync-feeds'
      preLoaderRoute: typeof ApiPublicSyncFeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp-webhook': {
      id: '/api/public/whatsapp-webhook'
      path: '/api/public/whatsapp-webhook'
      fullPath: '/api/public/whatsapp-webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ChatsRouteChildren {
  ChatsRoomIdRoute: typeof ChatsRoomIdRoute
}

const ChatsRouteChildren: ChatsRouteChildren = {
  ChatsRoomIdRoute: ChatsRoomIdRoute,
}

const ChatsRouteWithChildren = ChatsRoute._addFileChildren(ChatsRouteChildren)

interface CommunityRouteChildren {
  CommunitySpaceSlugRoute: typeof CommunitySpaceSlugRoute
}

const CommunityRouteChildren: CommunityRouteChildren = {
  CommunitySpaceSlugRoute: CommunitySpaceSlugRoute,
}

const CommunityRouteWithChildren = CommunityRoute._addFileChildren(
  CommunityRouteChildren,
)

interface MarketplaceRouteChildren {
  MarketplaceListingIdRoute: typeof MarketplaceListingIdRoute
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplaceListingIdRoute: MarketplaceListingIdRoute,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

interface PeopleRouteChildren {
  PeopleProfileIdRoute: typeof PeopleProfileIdRoute
}

const PeopleRouteChildren: PeopleRouteChildren = {
  PeopleProfileIdRoute: PeopleProfileIdRoute,
}

const PeopleRouteWithChildren =
  PeopleRoute._addFileChildren(PeopleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AuthRoute: AuthRoute,
  ChatsRoute: ChatsRouteWithChildren,
  CommunityRoute: CommunityRouteWithChildren,
  CommunityModerationRoute: CommunityModerationRoute,
  FeedsRoute: FeedsRoute,
  GroupsRoute: GroupsRoute,
  HealthRoute: HealthRoute,
  InboxRoute: InboxRoute,
  IntegrationsRoute: IntegrationsRoute,
  InterpretedRoute: InterpretedRoute,
  JoinRoute: JoinRoute,
  LogsRoute: LogsRoute,
  MarketplaceRoute: MarketplaceRouteWithChildren,
  MarketplaceNewRoute: MarketplaceNewRoute,
  McpRoute: McpRoute,
  MyEventsRoute: MyEventsRoute,
  MyListingsRoute: MyListingsRoute,
  MyProfileRoute: MyProfileRoute,
  NotificationsRoute: NotificationsRoute,
  PeopleRoute: PeopleRouteWithChildren,
  PublishedRoute: PublishedRoute,
  ReviewRoute: ReviewRoute,
  RulesRoute: RulesRoute,
  SettingsRoute: SettingsRoute,
  SubmitEventRoute: SubmitEventRoute,
  ToolManagementRoute: ToolManagementRoute,
  ToolsRoute: ToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  EventEditSubmissionIdRoute: EventEditSubmissionIdRoute,
  MarketplaceEditListingIdRoute: MarketplaceEditListingIdRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  ApiPublicEventsRoute: ApiPublicEventsRoute,
  ApiPublicMaintenanceRoute: ApiPublicMaintenanceRoute,
  ApiPublicSyncFeedsRoute: ApiPublicSyncFeedsRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
